config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :boards, only: [:index, :show, :new, :create]

  root 'boards#new'

  resources :recent_boards, only: [:index]
end

app/models/application_record.rb
# frozen_string_literal: true

# ApplicationRecord is the base class for all models in the application.
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
# frozen_string_literal: true

# Model representing a board in the application.
class Board < ApplicationRecord
  validates :width, :height, :mines, presence: true
  validate :mines_validation

  private

  def mines_validation
    max_allowed_mines = (0.15 * width.to_i * height.to_i).ceil

    return unless mines.to_i.negative? || mines.to_i > max_allowed_mines

    errors.add(:mines, "should be between 1 and #{max_allowed_mines}")
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
# frozen_string_literal: true

# The BoardsController handles interactions related to boards.
# It is responsible for managing and displaying boards.
class BoardsController < ApplicationController
  DEFAULT_PER_PAGE = 1

  before_action :set_board, only: [:show]

  def index
    @boards = Board.page(params[:page]).per(DEFAULT_PER_PAGE)
  end

  def show; end

  def new
    @board = Board.new
  end

  def create
    @board = BoardGeneratorService.new(board_params).call

    if @board
      redirect_to @board, notice: 'Board was successfully generated.'
    else
      flash.now[:alert] = 'Failed to generate the board. Please check your input.'
      render :new
    end
  end

  private

  def set_board
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:name, :email, :width, :height, :mines)
  end
end

app/controllers/recent_boards_controller.rb
# frozen_string_literal: true

# Controller responsible for handling recent boards-related actions.
class RecentBoardsController < ApplicationController
  RECENTLY_CREATED_PER_PAGE = 10

  def index
    @boards = Board.order(created_at: :desc).limit(RECENTLY_CREATED_PER_PAGE)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# ApplicationHelper module provides utility methods for views.
module ApplicationHelper
end

app/views/boards/_board.html.erb
<div id="<%= dom_id board %>">
  <%= render 'minesweeper_board', minesweeper_board: board.minesweeper_board, board: board %>
</div>

app/views/boards/_minesweeper_board.html.erb
<!-- app/views/your_controller/your_view.html.erb -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Minesweeper Board</title>
  <%= stylesheet_link_tag 'minesweeper' %>
</head>

<body>
<div class="minesweeper-board-container">
  <h1>Minesweeper Board</h1>
  <p>
    <strong>Name:</strong>
    <%= board.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= board.email %>
  </p>

  <p>
    <strong>Dimensions:</strong>
    <%= board.width %> x <%= board.height %>
  </p>

  <p>
    <strong>Mines:</strong>
    <%= board.mines %>
  </p>
  <% minesweeper_board = eval(minesweeper_board) %>
  <div class="minesweeper-board">
    <% minesweeper_board.each do |row| %>
      <div class="minesweeper-row">
        <% row.each do |cell| %>
          <div class="minesweeper-cell <%= cell == 9 ? 'mine' : (cell == 0 ? 'empty' : "number-#{cell}") %>">
            <% case cell %>
            <% when 9 %>
              💣
            <% when 0 %>
              ⬜
            <% else %>
              <%= cell %>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
</body>
</html>

app/views/boards/index.html.erb
<!-- app/views/boards/index.html.erb -->
<% @boards.each do |board| %>
  <%= render partial: 'board', locals: { board: board } %>
<% end %>

<div style="width: 100%; text-align: center;">
  <%= paginate @boards %>
</div>

<div style="width: 100%; text-align: center;">
  <%= link_to "Recently Created Boards", recent_boards_path, class: "btn btn-success btn-lg"%>
  <%= link_to "Create New Board", new_board_path, class: "btn btn-success btn-lg"%>
</div>

app/views/boards/new.html.erb
<!-- app/views/boards/new.html.erb -->

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href="https://fonts.googleapis.com/css?family=Cardo:700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,700" rel="stylesheet">

</head>

<body>
<div id="booking" class="section">
  <div class="col-md-12 mb-4 d-flex flex-column align-items-center justify-content-center">
    <%= link_to "Recently Created Boards", recent_boards_path, class: "btn btn-success btn-lg mb-2 custom-button"%>
    <%= link_to "All boards", boards_path, class: "btn btn-success btn-lg mb-2 custom-button_1"%>

  </div>
  <div class="section-center">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="booking-form">
            <div class="form-header">
              <h1>Generate Minesweeper Board</h1>
            </div>
            <%= form_with(model: @board, url: boards_path, method: :post, html: { onsubmit: 'return validateMines();' }) do |form| %>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <%= form.label :email, class: "form-label" %>
                    <%= form.text_field :email, class: "form-control", required: true %>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <%= form.label :name, class: "form-label" %>
                    <%= form.text_field :name, class: "form-control", required: true %>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-3">
                  <div class="form-group">
                    <%= form.label :width, class: "form-label" %>
                    <%= form.number_field :width, class: "form-control", required: true, min: 2 %>
                  </div>
                </div>
                <div class="col-md-3">
                  <div class="form-group">
                    <%= form.label :height, class: "form-label" %>
                    <%= form.number_field :height, class: "form-control", required: true, min: 2 %>
                  </div>
                </div>
                <div class="col-md-3">
                  <div class="form-group">
                    <%= form.label :mines, class: "form-label" %>
                    <%= form.number_field :mines, class: "form-control", required: true ,min: 1%>
                  </div>
                </div>
                <div class="col-md-3">
                  <div class="form-btn">
                    <%= form.submit "Generate Board", class: "submit-btn" %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</body>

</html>

app/views/boards/show.html.erb
<%= render 'minesweeper_board', minesweeper_board: @board.minesweeper_board, board: @board %>

<div style="width: 100%; text-align: center;">
  <%= link_to "Recently Created Boards", recent_boards_path, class: "btn btn-success btn-lg", style: "margin-right: 10px;" %>
  <%= link_to "All boards", boards_path, class: "btn btn-success btn-lg" %>
  <%= link_to 'Create New Board', new_board_path, class: 'btn btn-success btn-lg mb-2',style: "margin-left: 10px;" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>MinesweeperBoard</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZwT" crossorigin="anonymous">

  <%= stylesheet_link_tag "application", "bootstrap.min", "minesweeper_form", 'data-turbo-track': 'reload' %>
  <%= javascript_include_tag 'minesweeper_form', 'data-turbo-track': 'reload' %>
  <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js' %>

  <%= javascript_importmap_tags %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/recent_boards/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href="https://fonts.googleapis.com/css?family=Cardo:700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,700" rel="stylesheet">

  <%= stylesheet_link_tag 'bootstrap.min', 'data-turbo-track': 'reload' %>
  <%= stylesheet_link_tag 'minesweeper_form', 'data-turbo-track': 'reload' %>
  <%= javascript_include_tag 'minesweeper_form', 'data-turbo-track': 'reload' %>

  <style>
      .table th,
      .table td {
          font-size: 18px;
      }

      .btn-lg {
          font-size: 18px;
      }
  </style>
</head>

<body>
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h1>Recent Boards</h1>
      <table class="table table-striped table-hover">
        <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">Created At</th>
          <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        <% @boards.each_with_index do |board, index| %>
          <tr>
            <th scope="row"><%= index + 1 %></th>
            <td><%= board.name %></td>
            <td><%= board.email %></td>
            <td><%= board.created_at.strftime('%B %e, %Y %l:%M %p') %></td>
            <td>
              <%= link_to 'Show', board, class: 'btn btn-primary btn-sm' %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <%= link_to 'View All Boards', boards_path, class: 'btn btn-success btn-lg mb-2' %>
      <%= link_to 'Create New Board', new_board_path, class: 'btn btn-success btn-lg mb-2' %>


    </div>
  </div>
</div>
</body>

</html>